name: Java CI with Maven
on:
  push:
  schedule: # Every Monday
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Build and Test ${{ matrix.project }}
    runs-on: ubuntu-latest
    permissions: 
     contents: read
     security-events: write
    strategy:
      fail-fast: false
      matrix: 
       project: [
         catalog-service
       ]

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Setup JDK
       uses: actions/setup-java@v4
       with:
         distribution: temurin
         java-version: 17
         cache: maven
     - name: Build, unit tests and integration tests
       run: |
        cd ${{matrix.project}}
        chmod +x mvnw
        ./mvnw build
